import { ClerkProvider } from "@clerk/nextjs";
import "../globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "@/componenti/shared/Header";
import LeftSidebar from "@/componenti/shared/LeftSidebar";
import RightSidebar from "@/componenti/shared/RightSidebar";
import Footer from "@/componenti/shared/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Ulti",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <ClerkProvider>
            <html lang="en">
                <body className={inter.className}>
                    <Header />

                    <main className="flex flex-row">
                        <LeftSidebar />
                        <section className="main-container">
                            <div className="w-full max-w-4xl">{children}</div>
                        </section>
                        <RightSidebar />
                    </main>

                    <Footer />
                </body>
            </html>
        </ClerkProvider>
    );
}
